### ISSUE TITLE
build failed

### ISSUE THREAD

**Issue by picchiosat** [Avrahqedivra/xlxmond#1]
Hi,
I'm trying to install your dashboard for XLX but I get this error when I run: npm run build.
Debian 11 OS

root@test:/opt/xlxmond/src# npm run build

> monitor@1.0.0 build
> tsc

/opt/xlxmond/node_modules/typescript/lib/tsc.js:93
  for (let i = startIndex ?? 0; i < array.length; i++) {
                           ^

SyntaxError: Unexpected token '?'
    at wrapSafe (internal/modules/cjs/loader.js:915:16)
    at Module._compile (internal/modules/cjs/loader.js:963:27)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1027:10)
    at Module.load (internal/modules/cjs/loader.js:863:32)
    at Function.Module._load (internal/modules/cjs/loader.js:708:14)
    at Module.require (internal/modules/cjs/loader.js:887:19)
    at require (internal/modules/cjs/helpers.js:74:18)
    at Object.<anonymous> (/opt/xlxmond/node_modules/typescript/bin/tsc:2:1)
    at Module._compile (internal/modules/cjs/loader.js:999:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1027:10)
npm ERR! code 1
npm ERR! path /opt/xlxmond
npm ERR! command failed
npm ERR! command sh -c tsc

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2024-02-11T14_43_22_720Z-debug.log
root@test-jdv:/opt/xlxmond/src# nano /root/.npm/_logs/2024-02-11T14_43_22_720Z-debug.log
root@test-jdv:/opt/xlxmond/src# npm run build

> monitor@1.0.0 build
> tsc

/opt/xlxmond/node_modules/typescript/lib/tsc.js:93
  for (let i = startIndex ?? 0; i < array.length; i++) {
                           ^

SyntaxError: Unexpected token '?'
    at wrapSafe (internal/modules/cjs/loader.js:915:16)
    at Module._compile (internal/modules/cjs/loader.js:963:27)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1027:10)
    at Module.load (internal/modules/cjs/loader.js:863:32)
    at Function.Module._load (internal/modules/cjs/loader.js:708:14)
    at Module.require (internal/modules/cjs/loader.js:887:19)
    at require (internal/modules/cjs/helpers.js:74:18)
    at Object.<anonymous> (/opt/xlxmond/node_modules/typescript/bin/tsc:2:1)
    at Module._compile (internal/modules/cjs/loader.js:999:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1027:10)
npm ERR! code 1
npm ERR! path /opt/xlxmond
npm ERR! command failed
npm ERR! command sh -c tsc

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2024-02-11T18_16_43_588Z-debug.log
root@test:/opt/xlxmond/src#

73 de Roby IV3JDV

**Comment by Avrahqedivra** [comment]
which version of node are you running (must be greater than 18) ?

**Comment by picchiosat** [comment]
in fact...
Debian 11 repository install nodejs 12... updated... it works...
but the dashboard doesn't have the menus like the one in the link you sent me...
you can see it here: http://44.31.102.50:7779

**Comment by Avrahqedivra** [comment]
I tried to connect to your dashboard but it was not online. 

Send me a mails, I dont look to notifications here too frequently. 

73
